/**
 * ./mvnw clean idlj:generate
 */
module com {
  module example {
    module democorba {
        module service {
          typedef sequence<octet> BytesData;
          interface GreetingService
          {
            string hello(in string message);
            void execute(in BytesData request, out BytesData response);
          };
        };
    };
  };
};
